/* Copyright(c) Jada Informatique 2021.

Jada Informatique Software License - Version 1.0 - june 27th, 2021

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <nanodbc/nanodbc.h>
#include <string>
#include <vector>

// clang-format off
#include <windows.h>
#include <sqltypes.h>
#include <sqlucode.h>
// clang-format on


unsigned ExtractValue(const char* p, int len)
{
   unsigned result {};
   while (len-- > 0)
   {
      result <<= 8;
      result |= static_cast<unsigned>(p[len]) & 0xff;
   }
   return result;
}

struct OdbcInfoDesc
{
   std::string infoName;
   int         InfoIndex;
};
std::vector<OdbcInfoDesc> OdbcInfo = {
   {"SQL_COLLATION_SEQ", SQL_COLLATION_SEQ},
   {"SQL_NON_NULLABLE_COLUMNS", SQL_NON_NULLABLE_COLUMNS},
   {"SQL_DATABASE_NAME", SQL_DATABASE_NAME},
   {"SQL_DBMS_NAME", SQL_DBMS_NAME},
   {"SQL_DBMS_VER", SQL_DBMS_VER},
   {"SQL_AGGREGATE_FUNCTIONS", SQL_AGGREGATE_FUNCTIONS},
   {"SQL_ALTER_DOMAIN", SQL_ALTER_DOMAIN},
   {"SQL_ALTER_TABLE", SQL_ALTER_TABLE},
   {"SQL_CATALOG_LOCATION", SQL_CATALOG_LOCATION},
   {"SQL_CATALOG_NAME", SQL_CATALOG_NAME},
   {"SQL_CATALOG_NAME_SEPARATOR", SQL_CATALOG_NAME_SEPARATOR},
   {"SQL_CATALOG_USAGE", SQL_CATALOG_USAGE},
   {"SQL_COLUMN_ALIAS", SQL_COLUMN_ALIAS},
   {"SQL_CORRELATION_NAME", SQL_CORRELATION_NAME},
   {"SQL_CREATE_ASSERTION", SQL_CREATE_ASSERTION},
   {"SQL_CREATE_CHARACTER_SET", SQL_CREATE_CHARACTER_SET},
   {"SQL_CREATE_COLLATION", SQL_CREATE_COLLATION},
   {"SQL_CREATE_DOMAIN", SQL_CREATE_DOMAIN},
   {"SQL_CREATE_SCHEMA", SQL_CREATE_SCHEMA},
   {"SQL_CREATE_TABLE", SQL_CREATE_TABLE},
   {"SQL_CREATE_TRANSLATION", SQL_CREATE_TRANSLATION},
   {"SQL_DDL_INDEX", SQL_DDL_INDEX},
   {"SQL_DROP_ASSERTION", SQL_DROP_ASSERTION},
   {"SQL_DROP_CHARACTER_SET", SQL_DROP_CHARACTER_SET},
   {"SQL_DROP_COLLATION", SQL_DROP_COLLATION},
   {"SQL_DROP_DOMAIN", SQL_DROP_DOMAIN},
   {"SQL_DROP_SCHEMA", SQL_DROP_SCHEMA},
   {"SQL_DROP_TABLE", SQL_DROP_TABLE},
   {"SQL_DROP_TRANSLATION", SQL_DROP_TRANSLATION},
   {"SQL_DROP_VIEW", SQL_DROP_VIEW},
   {"SQL_EXPRESSIONS_IN_ORDERBY", SQL_EXPRESSIONS_IN_ORDERBY},
   {"SQL_GROUP_BY", SQL_GROUP_BY},
   {"SQL_IDENTIFIER_CASE", SQL_IDENTIFIER_CASE},
   {"SQL_IDENTIFIER_QUOTE_CHAR", SQL_IDENTIFIER_QUOTE_CHAR},
   {"SQL_INDEX_KEYWORDS", SQL_INDEX_KEYWORDS},
   {"SQL_INSERT_STATEMENT", SQL_INSERT_STATEMENT},
   {"SQL_INTEGRITY", SQL_INTEGRITY},
   {"SQL_KEYWORDS", SQL_KEYWORDS},
   {"SQL_OWNER_TERM", SQL_OWNER_TERM},
   {"SQL_LIKE_ESCAPE_CLAUSE", SQL_LIKE_ESCAPE_CLAUSE},
   {"SQL_OJ_CAPABILITIES", SQL_OJ_CAPABILITIES},
   {"SQL_ORDER_BY_COLUMNS_IN_SELECT", SQL_ORDER_BY_COLUMNS_IN_SELECT},
   {"SQL_OUTER_JOINS", SQL_OUTER_JOINS},
   {"SQL_PROCEDURES", SQL_PROCEDURES},
   {"SQL_QUOTED_IDENTIFIER_CASE", SQL_QUOTED_IDENTIFIER_CASE},
   {"SQL_SCHEMA_USAGE", SQL_SCHEMA_USAGE},
   {"SQL_SPECIAL_CHARACTERS", SQL_SPECIAL_CHARACTERS},
   {"SQL_SQL_CONFORMANCE", SQL_SQL_CONFORMANCE},
   {"SQL_SUBQUERIES", SQL_SUBQUERIES},
   {"SQL_UNION", SQL_UNION},
};


int main(int argc, char** argv)
{
   std::string database {argv[1]};
   auto        connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)};Dbq=" + database;

   try
   {
      nanodbc::connection conn(connection_string);
      for (auto infoDesc: OdbcInfo)
      {
         // SQLUSMALLINT
         char        collation[16300];
         SQLSMALLINT outLen {};
         auto        sqlStatus = SQLGetInfoA(conn.native_dbc_handle(), infoDesc.InfoIndex, collation, sizeof(collation), &outLen);
         if ((sqlStatus == SQL_SUCCESS || sqlStatus == SQL_SUCCESS_WITH_INFO) &&
             outLen > 0)
         {
            // if first char is a printable char assume we have a string, a bit bogus, but cheap fix until better solution
            if (isprint(collation[0]))
               std::cout << std::format("type {} : [{}] {} {}", infoDesc.infoName, collation, sqlStatus, outLen);
            else
               std::cout << std::format("type {} : [{}]", infoDesc.infoName, ExtractValue(collation, outLen));
         }

         else
         {
            std::cout << std::format("type {} : [Not implemented] {}", infoDesc.infoName, sqlStatus);
         }
         std::cout << std::endl;
      }
   }
   catch (std::exception& ex)
   {
   }
   return 0;
}